name: reproduction-check

on:
  pull_request:
    types: [opened, synchronize, ready_for_review]
    branches:
      - main
  push:
    branches:
        - main
  workflow_dispatch:

env:
  JDK_VERSION: 17

jobs:
  safety-check:
    name: Check for modified Gradle
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Validate Gradle artifacts
      uses: gradle/wrapper-validation-action@v1

  reproduction:
    name: Reproduction check
    needs: safety-check
    runs-on: ubuntu-latest
    # if: ${{ !github.event.pull_request.draft }}
    steps:
      - name: Checkout STARS
        uses: actions/checkout@v3
        # with:
          # fetch-depth: 0 # Required for version number generation & diff generation

      - name: Checkout STARS-CARLA
        uses: actions/checkout@v3
        with:
          repository: tudo-aqua/stars-carla-experiments
          ref: dev

      - name: TEST
        run: |
          echo ls -a
          cd ..
          echo ls -a
        
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ env.JDK_VERSION }}
